### Install REST Client extension for Visual Studio Code to use this file

### Post todo
POST http://localhost:8080/todos
content-type: application/json

{
  "description": "My todo!"
}


### Get all todos
GET http://localhost:8080/todos


### Get specific todo
GET http://localhost:8080/todos/3


### Update todo
PUT http://localhost:8080/todos/3
content-type: application/json

{
  "description": "Another todo..."
}


### Delete todo
DELETE http://localhost:8080/todos/3